# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_Refilled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RefilledAdd(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(362, 238)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 20, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 211, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_add_refilled = QtWidgets.QPushButton(Form)
        self.pb_add_refilled.setGeometry(QtCore.QRect(30, 200, 75, 23))
        self.pb_add_refilled.setObjectName("pb_add_refilled")
        self.pushButton_cansel_refilled = QtWidgets.QPushButton(Form)
        self.pushButton_cansel_refilled.setGeometry(QtCore.QRect(260, 200, 75, 23))
        self.pushButton_cansel_refilled.setObjectName("pushButton_cansel_refilled")
        self.lineEdit_place_establishment = QtWidgets.QLineEdit(Form)
        self.lineEdit_place_establishment.setGeometry(QtCore.QRect(10, 150, 340, 30))
        self.lineEdit_place_establishment.setObjectName("lineEdit_place_establishment")
        self.lineEdit_name_printer2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_name_printer2.setGeometry(QtCore.QRect(10, 60, 340, 30))
        self.lineEdit_name_printer2.setObjectName("lineEdit_name_printer2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Имя принтера "))
        self.label_2.setText(_translate("Form", "место установки"))
        self.pb_add_refilled.setText(_translate("Form", "Добавить"))
        self.pushButton_cansel_refilled.setText(_translate("Form", "отмена"))
