# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_On_clade.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(345, 306)
        self.pushButton_add_onclade = QtWidgets.QPushButton(Form)
        self.pushButton_add_onclade.setGeometry(QtCore.QRect(20, 260, 75, 23))
        self.pushButton_add_onclade.setObjectName("pushButton_add_onclade")
        self.pushButton_exit_onclade = QtWidgets.QPushButton(Form)
        self.pushButton_exit_onclade.setGeometry(QtCore.QRect(250, 260, 75, 23))
        self.pushButton_exit_onclade.setObjectName("pushButton_exit_onclade")
        self.lineEdit_nameprinter4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_nameprinter4.setGeometry(QtCore.QRect(10, 60, 320, 30))
        self.lineEdit_nameprinter4.setObjectName("lineEdit_nameprinter4")
        self.lineEdit_serial_number = QtWidgets.QLineEdit(Form)
        self.lineEdit_serial_number.setGeometry(QtCore.QRect(10, 130, 320, 30))
        self.lineEdit_serial_number.setObjectName("lineEdit_serial_number")
        self.lineEdit_port_number = QtWidgets.QLineEdit(Form)
        self.lineEdit_port_number.setGeometry(QtCore.QRect(10, 210, 320, 30))
        self.lineEdit_port_number.setObjectName("lineEdit_port_number")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(59, 19, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_add_onclade.setText(_translate("Form", "добавить"))
        self.pushButton_exit_onclade.setText(_translate("Form", "выход"))
        self.label.setText(_translate("Form", "имя принтера "))
        self.label_2.setText(_translate("Form", "серийный номер "))
        self.label_3.setText(_translate("Form", "порт номер "))
