# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_Refilled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(355, 489)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 20, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 211, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_add_refilled = QtWidgets.QPushButton(Form)
        self.pb_add_refilled.setGeometry(QtCore.QRect(20, 450, 75, 23))
        self.pb_add_refilled.setObjectName("pb_add_refilled")
        self.pushButton_cansel_refilled = QtWidgets.QPushButton(Form)
        self.pushButton_cansel_refilled.setGeometry(QtCore.QRect(260, 450, 75, 23))
        self.pushButton_cansel_refilled.setObjectName("pushButton_cansel_refilled")
        self.lineEdit_diagnostics = QtWidgets.QLineEdit(Form)
        self.lineEdit_diagnostics.setGeometry(QtCore.QRect(10, 150, 340, 30))
        self.lineEdit_diagnostics.setObjectName("lineEdit_diagnostics")
        self.lineEdit_name_printer2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_name_printer2.setGeometry(QtCore.QRect(10, 60, 340, 30))
        self.lineEdit_name_printer2.setObjectName("lineEdit_name_printer2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 190, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 320, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(90, 360, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_clearing = QtWidgets.QLineEdit(Form)
        self.lineEdit_clearing.setGeometry(QtCore.QRect(10, 220, 330, 30))
        self.lineEdit_clearing.setObjectName("lineEdit_clearing")
        self.lineEdit_testing_device = QtWidgets.QLineEdit(Form)
        self.lineEdit_testing_device.setGeometry(QtCore.QRect(10, 310, 340, 30))
        self.lineEdit_testing_device.setObjectName("lineEdit_testing_device")
        self.lineEdit_necessary = QtWidgets.QLineEdit(Form)
        self.lineEdit_necessary.setGeometry(QtCore.QRect(10, 400, 330, 30))
        self.lineEdit_necessary.setObjectName("lineEdit_necessary")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Имя принтера "))
        self.label_2.setText(_translate("Form", "Диагностика "))
        self.pb_add_refilled.setText(_translate("Form", "Добавить"))
        self.pushButton_cansel_refilled.setText(_translate("Form", "отмена"))
        self.label_3.setText(_translate("Form", "Очистка"))
        self.label_4.setText(_translate("Form", "Тестирование устройства"))
        self.label_5.setText(_translate("Form", "Необходимый"))
