# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(329, 284)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_auth = QtWidgets.QPushButton(self.centralwidget)
        self.pb_auth.setGeometry(QtCore.QRect(40, 220, 100, 30))
        self.pb_auth.setStyleSheet("")
        self.pb_auth.setObjectName("pb_auth")
        self.pb_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pb_exit.setGeometry(QtCore.QRect(210, 220, 90, 30))
        self.pb_exit.setStyleSheet("")
        self.pb_exit.setObjectName("pb_exit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 110, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.lineEdit_log = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_log.setGeometry(QtCore.QRect(30, 70, 250, 30))
        self.lineEdit_log.setObjectName("lineEdit_log")
        self.lineEdit_psw = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_psw.setGeometry(QtCore.QRect(30, 170, 250, 30))
        self.lineEdit_psw.setObjectName("lineEdit_psw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.pb_auth.setText(_translate("MainWindow", "Вход"))
        self.pb_exit.setText(_translate("MainWindow", "Выход"))
        self.label.setText(_translate("MainWindow", "Логин"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
