# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_defective.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Delete_Defective(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(486, 135)
        self.pb_yes_defective = QtWidgets.QPushButton(Form)
        self.pb_yes_defective.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.pb_yes_defective.setObjectName("pb_yes_defective")
        self.pB_no_defective = QtWidgets.QPushButton(Form)
        self.pB_no_defective.setGeometry(QtCore.QRect(390, 90, 75, 23))
        self.pB_no_defective.setObjectName("pB_no_defective")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 410, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Удаление неисправном "))
        self.pb_yes_defective.setText(_translate("Form", "да "))
        self.pB_no_defective.setText(_translate("Form", "нет "))
        self.label.setText(_translate("Form", "Вы точно хотите удалить строку "))
