from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1241, 690)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView_Department = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Department.setGeometry(QtCore.QRect(10, 50, 291, 391))
        self.tableView_Department.setObjectName("tableView_Department")
        self.label_Department = QtWidgets.QLabel(self.centralwidget)
        self.label_Department.setGeometry(QtCore.QRect(20, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Department.setFont(font)
        self.label_Department.setObjectName("label_Department")
        self.pushButton_Department_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Department_add.setGeometry(QtCore.QRect(10, 460, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Department_add.setFont(font)
        self.pushButton_Department_add.setObjectName("pushButton_Department_add")
        self.pushButton_Department_remove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Department_remove.setGeometry(QtCore.QRect(160, 460, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Department_remove.setFont(font)
        self.pushButton_Department_remove.setObjectName("pushButton_Department_remove")
        self.pushButton_Department_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Department_delete.setGeometry(QtCore.QRect(80, 510, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Department_delete.setFont(font)
        self.pushButton_Department_delete.setObjectName("pushButton_Department_delete")
        self.tableView_Ward = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Ward.setGeometry(QtCore.QRect(320, 50, 291, 391))
        self.tableView_Ward.setObjectName("tableView_Ward")
        self.label_Ward = QtWidgets.QLabel(self.centralwidget)
        self.label_Ward.setGeometry(QtCore.QRect(320, 2, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Ward.setFont(font)
        self.label_Ward.setObjectName("label_Ward")
        self.pushButton_Ward_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Ward_add.setGeometry(QtCore.QRect(320, 460, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Ward_add.setFont(font)
        self.pushButton_Ward_add.setObjectName("pushButton_Ward_add")
        self.pushButton_Ward_remove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Ward_remove.setGeometry(QtCore.QRect(470, 460, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Ward_remove.setFont(font)
        self.pushButton_Ward_remove.setObjectName("pushButton_Ward_remove")
        self.pushButton_Ward_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Ward_delete.setGeometry(QtCore.QRect(390, 510, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Ward_delete.setFont(font)
        self.pushButton_Ward_delete.setObjectName("pushButton_Ward_delete")
        self.tableView_Patient = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Patient.setGeometry(QtCore.QRect(630, 50, 291, 391))
        self.tableView_Patient.setObjectName("tableView_Patient")
        self.pushButton_Patient_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Patient_add.setGeometry(QtCore.QRect(630, 460, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Patient_add.setFont(font)
        self.pushButton_Patient_add.setObjectName("pushButton_Patient_add")
        self.pushButton_Patient_remove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Patient_remove.setGeometry(QtCore.QRect(780, 460, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Patient_remove.setFont(font)
        self.pushButton_Patient_remove.setObjectName("pushButton_Patient_remove")
        self.pushButton_Patient_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Patient_delete.setGeometry(QtCore.QRect(700, 510, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Patient_delete.setFont(font)
        self.pushButton_Patient_delete.setObjectName("pushButton_Patient_delete")
        self.tableView_Procedure = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Procedure.setGeometry(QtCore.QRect(940, 50, 291, 391))
        self.tableView_Procedure.setObjectName("tableView_Procedure")
        self.pushButton_Procedure_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Procedure_add.setGeometry(QtCore.QRect(940, 460, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Procedure_add.setFont(font)
        self.pushButton_Procedure_add.setObjectName("pushButton_Procedure_add")
        self.pushButton_Procedure_remove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Procedure_remove.setGeometry(QtCore.QRect(1090, 460, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Procedure_remove.setFont(font)
        self.pushButton_Procedure_remove.setObjectName("pushButton_Procedure_remove")
        self.pushButton_Procedure_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Procedure_delete.setGeometry(QtCore.QRect(1010, 510, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Procedure_delete.setFont(font)
        self.pushButton_Procedure_delete.setObjectName("pushButton_Procedure_delete")
        self.label_Patients = QtWidgets.QLabel(self.centralwidget)
        self.label_Patients.setGeometry(QtCore.QRect(630, 0, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Patients.setFont(font)
        self.label_Patients.setObjectName("label_Patients")
        self.label_Procedure = QtWidgets.QLabel(self.centralwidget)
        self.label_Procedure.setGeometry(QtCore.QRect(940, 0, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_Procedure.setFont(font)
        self.label_Procedure.setObjectName("label_Procedure")
        self.pushButton_Report = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Report.setGeometry(QtCore.QRect(540, 630, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Report.setFont(font)
        self.pushButton_Report.setObjectName("pushButton_Report")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Department.setText(_translate("MainWindow", "Отделение"))
        self.pushButton_Department_add.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_Department_remove.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_Department_delete.setText(_translate("MainWindow", "Удалить"))
        self.label_Ward.setText(_translate("MainWindow", "Палаты"))
        self.pushButton_Ward_add.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_Ward_remove.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_Ward_delete.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_Patient_add.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_Patient_remove.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_Patient_delete.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_Procedure_add.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_Procedure_remove.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_Procedure_delete.setText(_translate("MainWindow", "Удалить"))
        self.label_Patients.setText(_translate("MainWindow", "Больные"))
        self.label_Procedure.setText(_translate("MainWindow", "Процедуры"))
        self.pushButton_Report.setText(_translate("MainWindow", "Отчёт"))
